export const FETCH_GUILDS = "FETCH_GUILDS";
export const FETCH_GUILD = "FETCH_GUILD";
export const FETCH_GUILD_MEMBERS = "FETCH_GUILD_MEMBERS";
export const FETCH_GUILD_EVENT_STATS = "FETCH_GUILD_EVENT_STATS";
export const FETCH_MEMBER = "FETCH_MEMBER";
export const FETCH_MEMBER_EVENT_STAT = "FETCH_MEMBER_EVENT_STAT";
export const FETCH_MEMBER_EVENTS = "FETCH_MEMBER_EVENTS";
export const FETCH_EVENTS_LIST = "FETCH_EVENTS_LIST";
export const FETCH_EVENT = "FETCH_EVENT";
export const CLEAR_MEMBER = "CLEAR_MEMBER";
export const CLEAR_MEMBER_EVENT_STAT = "CLEAR_MEMBER_EVENT_STAT";

