export const FETCH_GUILDS = "FETCH_GUILDS";
export const FETCH_GUILD = "FETCH_GUILD";
export const FETCH_GUILD_MEMBERS = "FETCH_GUILD_MEMBERS";
export const FETCH_MEMBER_EVENT_STAT = "FETCH_MEMBER_EVENT_STAT";
export const FETCH_MEMBER_EVENTS = "FETCH_MEMBER_EVENTS";
